dist: jammy
language: python
python: 3.9
services:
- docker
before_install:
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.3.0/buildx-v0.3.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
install:
- pip install pipenv
- pipenv sync
env:
  global:
  - PY_COLOR=1
  - ANSIBLE_FORCE_COLOR=1
  - secure: Iw1sHxmjqF6LPywwMPqbogZ47ZnSWPEDq8k71iqKfao0mDtLMUcmF2yIMLC0MQg1akaBKeHBS4MBQVBaGJDz++rgByzVpHwM0S0ZwUiO2ffVQE4uI+JSEMc1R34/5QPkYsg0FSIDVsCZZ9VnRLKh3GnVHlUljwwfVX5UX0g8RDEHxgdYSGGdAt8iUlQ3/YPSkvuKuNPWHtXCM0tkRYByUVUugSwUuo3rolYVv/S8AcrDf9qhHNkrp4zglC31wurq3M0yjmwHnShl+bLj2lV+QAenmFfjAZWlZ3DxARnSWSlFHMT3PGGWHYpFr2BN/na9ZQqmbWcR8k8XKFv6O205M+Zqao1zvzEpWVZBBiBJwYEVekQk1CzpVQ73sitYLHnmPNK5+W4939dNCkKocNhDf/bJTtaU/JlA64418N4hdjBsXTRfhzAILYJ0ba6a8Qnh5Xeuu3EZlRx6JepYEzy5dJel11MgDNVvaC8r9plCYtfo2ew1OH5QcDqCeaU+hTuXB02tNDWQoXP+aInF4JFqxWuEOlpGZeI3lXKNyHADaNBfziwWwtmBqHKhiLn7a8RJSSrVHRY0LS2YfAi5h4R3YwORlPr9E3I8Sgss21X1D2ocOMjZ4Qdfo5/eteUmEqq3yZBzeynrUwoSR7NYzllVWXMLMOoda2kckXNGaD5U7Es=
  jobs:
  # Java 8
  - DOCKER_IMAGE_BASE=debian:bookworm-slim JDK_VENDOR=temurin JDK_MAJOR=8 JDK_VERSION=8.0.382.0.0+5
    DOCKER_TAG_TO_PUBLISH=8u382-bookworm-temurin-jdk
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=temurin JDK_MAJOR=8 JDK_VERSION=8.0.382.0.0+5
    DOCKER_TAG_TO_PUBLISH=8u382-bullseye-temurin-jdk
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=temurin JDK_MAJOR=8 JDK_VERSION=8.0.382.0.0+5
    DOCKER_TAG_TO_PUBLISH=8u382-buster-temurin-jdk
  - DOCKER_IMAGE_BASE=debian:stretch-slim JDK_VENDOR=temurin JDK_MAJOR=8 JDK_VERSION=8.0.322.0.0+6-1
    DOCKER_TAG_TO_PUBLISH=8u322-buster-temurin-jdk

  - DOCKER_IMAGE_BASE=debian:stretch-slim JDK_MAJOR=8 DOCKER_TAG_TO_PUBLISH=8-stretch-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:bionic JDK_MAJOR=8 JDK_VERSION=8u372-ga~us1-0ubuntu1~18.04
    DOCKER_TAG_TO_PUBLISH=8u372-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=8 JDK_VERSION=8u382-ga-1~20.04.1
    DOCKER_TAG_TO_PUBLISH=8u382-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=8 JDK_VERSION=8u402-ga-2ubuntu1~22.04
    DOCKER_TAG_TO_PUBLISH=8u402-jammy-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_VENDOR=temurin JDK_MAJOR=8 JDK_VERSION=8.0.382.0.0+5
    DOCKER_TAG_TO_PUBLISH=8u382-focal-temurin-jdk
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_VENDOR=temurin JDK_MAJOR=8 JDK_VERSION=8.0.382.0.0+5
    DOCKER_TAG_TO_PUBLISH=8u382-jammy-temurin-jdk

  - DOCKER_IMAGE_BASE=debian:bookworm-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-bookworm-corretto-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-bullseye-corretto-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-buster-corretto-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_VENDOR=corretto JDK_MAJOR=1.8.0
    JDK_VERSION=1.8.0_302.b08 DOCKER_TAG_TO_PUBLISH=8u302-centos8-corretto-headless

  # Java 11
  - DOCKER_IMAGE_BASE=debian:buster-slim DOCKER_TAG_TO_PUBLISH=11-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_MAJOR=11 JDK_VERSION=11.0.18+10-1~deb10u1
    DOCKER_TAG_TO_PUBLISH=11.0.18-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim DOCKER_TAG_TO_PUBLISH=11-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=11 JDK_VERSION=11.0.20+8-1~deb11u1
    DOCKER_TAG_TO_PUBLISH=11.0.20-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bookworm-slim DOCKER_TAG_TO_PUBLISH=11-bookworm-openjdk-headless

  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_MAJOR=11 JDK_VENDOR=temurin JDK_VERSION=11.0.20.0.0+8
    DOCKER_TAG_TO_PUBLISH=11.0.20-buster-temurin-jdk
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=11 JDK_VENDOR=temurin JDK_VERSION=11.0.20.0.0+8
    DOCKER_TAG_TO_PUBLISH=11.0.20-bullseye-temurin-jdk
  - DOCKER_IMAGE_BASE=debian:bookworm-slim JDK_MAJOR=11 JDK_VENDOR=temurin JDK_VERSION=11.0.20.0.0+8
    DOCKER_TAG_TO_PUBLISH=11.0.20-bookworm-temurin-jdk

  - DOCKER_IMAGE_BASE=ubuntu:bionic DOCKER_TAG_TO_PUBLISH=11-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:bionic JDK_MAJOR=11 JDK_VERSION=11.0.19+7~us1-0ubuntu1~18.04.1
    DOCKER_TAG_TO_PUBLISH=11.0.19-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal DOCKER_TAG_TO_PUBLISH=11-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=11 JDK_VERSION=11.0.20+8-1ubuntu1~20.04
    DOCKER_TAG_TO_PUBLISH=11.0.20-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy DOCKER_TAG_TO_PUBLISH=11-jammy-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=11 JDK_VERSION=11.0.22+7-0ubuntu2~22.04.1
    DOCKER_TAG_TO_PUBLISH=11.0.22-jammy-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=11 JDK_VENDOR=temurin JDK_VERSION=11.0.20.0.0+8
    DOCKER_TAG_TO_PUBLISH=11.0.20-focal-temurin-jdk
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=11 JDK_VENDOR=temurin JDK_VERSION=11.0.20.0.0+8
    DOCKER_TAG_TO_PUBLISH=11.0.20-jammy-temurin-jdk

  - DOCKER_IMAGE_BASE=centos:7 JDK_MAJOR=11 JDK_VERSION=11.0.12.0.7 DOCKER_TAG_TO_PUBLISH=11.0.12.0.7-centos7-openjdk-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_MAJOR=11 JDK_VERSION=11.0.13.0.8
    DOCKER_TAG_TO_PUBLISH=11.0.13.0.8-centos8-openjdk-headless

  # SSL certificates scenario  
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=openjdk-certs

  # Java 17
  - DOCKER_IMAGE_BASE=debian:bullseye-slim DOCKER_TAG_TO_PUBLISH=17-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=17 JDK_VERSION=17.0.7+7-1~deb11u1
    DOCKER_TAG_TO_PUBLISH=17.0.7-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bookworm-slim JDK_MAJOR=17 JDK_VERSION=17.0.8+7-1~deb12u1
    DOCKER_TAG_TO_PUBLISH=17.0.8-bookworm-openjdk-headless

  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=17 JDK_VENDOR=temurin JDK_VERSION=17.0.8.0.0+7
    DOCKER_TAG_TO_PUBLISH=17.0.8-bullseye-temurin-jdk
  - DOCKER_IMAGE_BASE=debian:bookworm-slim JDK_MAJOR=17 JDK_VENDOR=temurin JDK_VERSION=17.0.8.0.0+7
    DOCKER_TAG_TO_PUBLISH=17.0.8-bookworm-temurin-jdk

  - DOCKER_IMAGE_BASE=ubuntu:focal DOCKER_TAG_TO_PUBLISH=17-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=17 JDK_VERSION=17.0.8+7-1~20.04.2
    DOCKER_TAG_TO_PUBLISH=17.0.8-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy DOCKER_TAG_TO_PUBLISH=17-jammy-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=17 JDK_VERSION=17.0.10+7-1~22.04.1
    DOCKER_TAG_TO_PUBLISH=17.0.10-jammy-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=17 JDK_VENDOR=temurin JDK_VERSION=17.0.8.0.0+7
    DOCKER_TAG_TO_PUBLISH=17.0.8-focal-temurin-jdk
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=17 JDK_VENDOR=temurin JDK_VERSION=17.0.8.0.0+7
    DOCKER_TAG_TO_PUBLISH=17.0.8-jammy-temurin-jdk

script:
- docker --version
- docker buildx version
- pipenv run molecule test --scenario-name=${JDK_VENDOR:-default}
notifications:
  webhooks:
  - https://galaxy.ansible.com/api/v1/notifications/
deploy:
  provider: script
  script: ANSIBLE_ROLES_PATH=../ pipenv run ansible-playbook dockerhub/main.yml --extra-vars "docker_hub_email=${DOCKER_EMAIL} docker_hub_username=${DOCKER_USERNAME} docker_hub_password=${DOCKER_PASS} docker_image_base=${DOCKER_IMAGE_BASE} jdk_version=${JDK_VERSION} jdk_major=${JDK_MAJOR} jdk_vendor=${JDK_VENDOR}  docker_tag=${DOCKER_TAG_TO_PUBLISH}"

  on:
    branch: master
    condition: "$JDK_VERSION"
